# Generated by Django 5.2.17 on 2026-09-10 08:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('copies', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_recurring', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('vehicle', models.CharField(max_length=40)),
                ('driver', models.CharField(blank=True, max_length=80)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CampusOS Academy', max_length=160)),
                ('motto', models.CharField(blank=True, default='Learn with honour.', max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('theme', models.CharField(default='ivory', max_length=16)),
                ('language', models.CharField(default='en', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=24)),
                ('body', models.CharField(max_length=480)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('held_on', models.DateField()),
                ('max_marks', models.PositiveSmallIntegerField(default=100)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relation', models.CharField(default='Parent', max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('period', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_on', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('part', 'Partial'), ('void', 'Void')], default='open', max_length=8)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.feehead')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('audience', models.CharField(default='all', max_length=16)),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(default='cash', max_length=12)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('parent', 'Parent'), ('student', 'Student')], default='teacher', max_length=16)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('theme', models.CharField(default='ivory', max_length=16)),
                ('language', models.CharField(default='en', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.klass')),
            ],
            options={
                'ordering': ['klass__rank', 'name'],
                'unique_together': {('klass', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('born_on', models.DateField()),
                ('status', models.CharField(choices=[('app', 'Applicant'), ('ok', 'Enrolled'), ('al', 'Alumni'), ('left', 'Left')], default='app', max_length=8)),
                ('admitted_on', models.DateField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.guardian')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='core.route')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_on', models.DateField()),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.student')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.student'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.klass')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('designation', models.CharField(max_length=80)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('mark', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='P', max_length=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('slot', models.PositiveSmallIntegerField()),
                ('starts', models.TimeField()),
                ('ends', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='core.section')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'ordering': ['weekday', 'slot'],
                'unique_together': {('section', 'weekday', 'slot')},
            },
        ),
    ]
