# Generated by Django 5.2.17 on 2026-09-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(default='http', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('severity', models.CharField(default='sev2', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ack', 'Acknowledged'), ('res', 'Resolved')], default='open', max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='OnCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oncall', to='core.site')),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='core.site'),
        ),
        migrations.AlterUniqueTogether(
            name='monitor',
            unique_together={('site', 'name')},
        ),
    ]
