# Generated by Django 5.2.17 on 2026-09-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('client', models.CharField(max_length=80)),
                ('rate', models.DecimalField(decimal_places=2, default=8000, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('bill', 'Billing'), ('close', 'Closed')], default='open', max_length=8)),
                ('retainer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued', models.DateField(auto_now_add=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.matter')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField()),
                ('note', models.CharField(max_length=200)),
                ('billed', models.BooleanField(default=False)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.matter')),
            ],
        ),
    ]
