# Generated by Django 5.2.17 on 2026-09-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(default='roads', max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('work', 'In works'), ('done', 'Resolved'), ('dup', 'Duplicate')], default='open', max_length=8)),
                ('reporter', models.CharField(max_length=80)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.ward')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.CharField(max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('closed', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.issue')),
            ],
        ),
    ]
