# Generated by Django 5.2.17 on 2026-09-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('licence', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('suburb', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('beds', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('live', 'Live'), ('hold', 'Under offer'), ('sold', 'Sold'), ('off', 'Withdrawn')], default='live', max_length=8)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('win', 'Accepted'), ('lose', 'Declined')], default='open', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('visitor', models.CharField(max_length=80)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='core.listing')),
            ],
            options={
                'unique_together': {('listing', 'when', 'visitor')},
            },
        ),
    ]
