# Generated by Django 5.2.17 on 2026-09-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=22, unique=True)),
                ('sender', models.CharField(max_length=80)),
                ('recipient', models.CharField(max_length=80)),
                ('dest_city', models.CharField(max_length=60)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('new', 'Created'), ('hub', 'At hub'), ('out', 'Out for delivery'), ('done', 'Delivered'), ('ret', 'Returned')], default='new', max_length=8)),
                ('cod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.courier')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound', to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.parcel')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couriers', to='core.station'),
        ),
    ]
