# Generated by Django 5.2.17 on 2026-09-10 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('target_url', models.URLField(help_text='Where the short link sends visitors.', max_length=500)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('tags', models.CharField(blank=True, help_text='Optional comma-separated tags.', max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_clicks', models.PositiveIntegerField(blank=True, help_text='Stop redirecting after this many clicks.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('click_count', models.PositiveIntegerField(default=0, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='core.shortlink')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=8)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='core.shortlink')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='shortlink',
            index=models.Index(fields=['owner', '-created'], name='core_shortl_owner_i_0e52bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyrollup',
            constraint=models.UniqueConstraint(fields=('link', 'date'), name='one_rollup_per_link_per_day'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['link', '-created'], name='core_click_link_id_902977_idx'),
        ),
    ]
