# Generated by Django 5.2.17 on 2026-09-11 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.SlugField(unique=True)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=22, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('memo', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('post', 'Posted'), ('void', 'Void')], default='post', max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_transfers', to='core.account')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='out_transfers', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.account')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.transfer')),
            ],
        ),
    ]
